### ISSUE TITLE
It doesn't work in the version of polymer#2.0.0

### ISSUE THREAD

**Issue by youlaiyouqudeyu** [ergo/polymer-dragula#12]

**Comment by jukbot** [comment]
same issue here 😞  this repo is outdated for a long time.

**Comment by ergo** [comment]
Can you provide some error stack traces?

**Comment by zichenma** [comment]
Yeah, for polymer2, it won't work. I got this error: polymer-dragula.html:188 Uncaught TypeError: this.queryAllEffectiveChildren is not a function
